sudo: required

language: go

services:
  - docker

before_install:
	- docker login -e="$DOCKER_HUB_EMAIL" -u="$DOCKER_HUB_USERNAME" -p="$DOCKER_HUB_PASSWORD"

install:
	- docker build --no-cache -t celestialstats/clientdiscord:latest .

after_success:
	- docker push celestialstats/clientdiscord:latest
